version: '3.8'

services:
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./data/redis:/data"
  api:
    build: .
    tty: true
    volumes:
      - .:/go/src/api
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: air
