# 青字は提供されているもの

# 橙字のコロンの左側 ホストOSのファイル群
# 橙字のコロンの右側 コンテナのパス

version: '3'

services:
  db:
    container_name: oc-db
    image: postgres:14
    volumes:
      - oc-db-volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  api:
    container_name: oc-api
    build: .
    tty: true
    volumes:
      - .:/go/src/api
    ports:
      - '8000:8080'
    depends_on:
      - db
  adminer:
    container_name: oc-adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  oc-db-volume:


